### ISSUE TITLE
Plan for secure storage

### ISSUE THREAD

**Issue by jenkijo** [LtbLightning/bdk-rn#2]
Currently, `bdk-rn` only store plain data (seedphase, password,..) in `localstorage` that cause critical security issue. I glad to help you make change via PR, my plan is switch from `localstorage` to [react-native-keychain](https://github.com/oblador/react-native-keychain), but what do you think about it?

If everything is clear, I will create a PR for it.

**Comment by BitcoinZavior** [comment]
@jenkijo thanks for the suggestion. Ideally the mnemonic or any other user wallet data should be secured by the app which will use `bdk-rn`. bdk-rn should only create the mnemonic and provide it to the app, its the app architecture which needs to account for secure storage.

The latest updates to `bdk-rn` remove `async-storage` dependency and do not store the mnemonic.

**Comment by BitcoinZavior** [comment]
@jenkijo I am closing this issue. You are welcome to look at other open issues to work on 😊
