### ISSUE TITLE
`wallet.sync()` is blocking execution on android

### ISSUE THREAD

**Issue by Czino** [LtbLightning/bdk-rn#45]
Combined with issue https://github.com/LtbLightning/bdk-rn/issues/44, this becomes quickly problematic.

Performing a `wallet.sync()` on app init result in at least 10 seconds waiting time.

Any other `wallet.sync()` during the session makes the app unresponsive

**Comment by BitcoinZavior** [comment]
@Czino Please check these changes https://github.com/LtbLightning/bdk-rn/pull/48
Execution is not blocked anymore using this approach.
I am not sure about the UI but code execution doesn't wait for the sync process to complete.
