### ISSUE TITLE
Syncing blocks main thread on iOS now

### ISSUE THREAD

**Issue by Czino** [LtbLightning/bdk-rn#52]
I found that the change made in this line
https://github.com/LtbLightning/bdk-rn/blob/b31ab3dca45ddb4d98a56ecf2e8effdec54b201e/ios/BdkRnModule.swift#LL497C15-L497C15

Is now blocking the main thread iOS. Reverting the change fixes the issue.

**Comment by BitcoinZavior** [comment]
The fix is in https://github.com/LtbLightning/bdk-rn/pull/54
Will merge it after you can confirm if works for you.
