### ISSUE TITLE
java.lang.String cannot be cast to java.lang.Double

### ISSUE THREAD

**Issue by robertclarkson** [LtbLightning/bdk-rn#57]
using version 0.1.1

```
java.lang.String cannot be cast to java.lang.Double
```

seems to crash with the electrum config.

```
const config: BlockchainElectrumConfig = {
  url: 'ssl://electrum.blockstream.info:60002',
  retry: '5',
  timeout: '5',
  stopGap: '5',
};
```

**Comment by robertclarkson** [comment]
I should add I've tried changing the values from strings to doubles. No dice.

**Comment by BitcoinZavior** [comment]
@robertclarkson Please use the main branch, that should work fine.

**Comment by robertclarkson** [comment]
@BitcoinZavior Appologies, this error was actually from the main branch - I've tried both...

**Comment by Czino** [comment]
Hi @robertclarkson, use integers instead of strings, see the type of the `BlockchainElectrumConfig`:

```
export interface BlockchainElectrumConfig {
    url: string;
    sock5: string | null;
    retry: number;
    timeout: number;
    stopGap: number;
    validateDomain: boolean;
}
```

@BitcoinZavior I see the example in the README is misleading. Let me create a PR to fix it

**Comment by robertclarkson** [comment]
Nice one. That fixed it for me. Thank you @Czino !!
