### ISSUE TITLE
When will this lib upgrade to the latest version of BDK 0.29.0 ?

### ISSUE THREAD

**Issue by robertclarkson** [LtbLightning/bdk-rn#60]
Hi guys, thanks for this great lib. 

We're using it to make a new kind of wallet.

We need to access the public key byte array value from the Script class in order to construct a new transaction adding a hash time lock. The byte array is abstracted away and we have no access to it. We can access it in version 0.29 of BDK but this library is on 0.27.1

Any idea when the new version will be available?

We've had a go at upgrading the library ourselves but we're not too sure what we're doing and its giving us lots of errors.

Thanks

**Comment by BitcoinZavior** [comment]
@robertclarkson Great to know 👍
Please check now, v29 changes have been added. Would love your feedback.

**Comment by robertclarkson** [comment]
Awesome @BitcoinZavior great work! I will check it out. 

I might put in a pull request for AddressIndex.Peek
